### ISSUE TITLE
能写个防止按钮快速点击的吗

### ISSUE THREAD

**Issue by zhaolijunstar** [Leaking/Hunter#12]

**Comment by miaorenjie** [comment]
这个业务方做合适一点吧，aop防抖会导致不熟悉项目的新人遇到问题Debug一天都不能解决

**Comment by zhaolijunstar** [comment]
> 这个业务方做合适一点吧，aop防抖会导致不熟悉项目的新人遇到问题Debug一天都不能解决

会有啥bug和这个相关？

**Comment by liangxiwei** [comment]
我想问下这些修改字节码的，一般是怎么对应到开发流程上的，比如修改了字节码，debug的时候应该会出现代码和行号对应不上的情况吧？难道是release的时候才打开AOP，只在需要加AOP的时候才打开调试？

**Comment by Leaking** [comment]
几个插件都处理了行号的问题，不会影响原有代码的行号。
可以看看这篇文章http://quinnchen.me/2018/09/13/2018-09-13-asm-transform/

**Comment by xymelon** [comment]
> 几个插件都处理了行号的问题，不会影响原有代码的行号。
> 可以看看这篇文章http://quinnchen.me/2018/09/13/2018-09-13-asm-transform/

上面这链接打不开呢。。。有新的文章推荐吗？谢谢

**Comment by Leaking** [comment]
@xymelon 抱歉，博客这几天挂了，可以看公众号上的文章
https://mp.weixin.qq.com/s/6lrYIkl5DTkbJuaayEQslQ
