### ISSUE TITLE
[DebugPlugin]可以支持一系列方法的统计吗

### ISSUE THREAD

**Issue by joware** [Leaking/Hunter#14]
比如某个业务流程，从开始的方法到最后结束的方法，中间可能有许多个方法调用，通过标记开始和结束的方法调用，统计出这个业务的耗时，如果要做到这个，怎么修改比较好呢

**Comment by Leaking** [comment]
1、这里说的整个业务流程，可能是同个线程中的业务，也可能是跨越多个线程的业务。
2、对于同个线程中的业务，能否将整个业务通过一个外层的函数收拢，然后统计这个最外层函数的耗时。目前DebugPlugin就已经支持这种场景了。
3、如果是跨越多个线程的业务，就可能需要做特殊处理了，需要在业务开始处加一个类似`@HunterDebugStart('xxx')`的注解（xxx代表业务名字，具备业务唯一性），然后在业务出口方法加一个类似`@HunterDebugEnd(`xxx`)`的注解。然后写一个插件，统计所有同个业务名字下，@HunterDebugEnd - @HunterDebugStart 的时间

**Comment by joware** [comment]
嗯，一般都是跨越多个线程的业务，标记业务用Start/End是个不错的方法，可能需要增加额外的参数，用于区分同一个业务反复发生的情况，连续发生的业务会存在时间交错的情况。
