### ISSUE TITLE
能否在BaseWeaver中暴露出来删除class的能力？

### ISSUE THREAD

**Issue by xingchenxuanfeng** [Leaking/Hunter#17]
我希望写的插件中带有这样的功能：删除指定的class，但是现在hunter中只能修改class，而不能删除，我看了BaseWeaver中的weaveJar和weaveSingleClassToFile这两个方法看起来适合做这种功能。
奈何这两个方法都标记为final方法，我没有办法进行重写。

可否把这两个方法的final修饰符去掉。

或者在这两个方法中，加入删除class的支持，我觉得应该只要加入weaveSingleClassToByteArray返回值为空的时候，不进行新文件或新ZipEntry的创建就可以了。

**Comment by Leaking** [comment]
能否描述一下，删除class是用于什么具体场景呢？

**Comment by xingchenxuanfeng** [comment]
没关系，我已经解决了。
我发现我实际的需求，不是删除class，而是删除class中的变量和方法，而如果一个类没有任何变量和方法，也就没有其他类去引用它，在混淆的时候也就会自动删除它。
