### ISSUE TITLE
类的方法耗时监控

### ISSUE THREAD

**Issue by pk00789o** [Leaking/Hunter#18]
如题，能否为class加上注解，把这个class的所有方法都加上耗时监控，单个方法加效率比较低。

**Comment by stfnt** [comment]
hello，我添加了HunterDebugClass和HunterDebugSkip用来支持将这个class的所有方法都加上耗时监控
这是我的对比文件
package com.quinn.hunter.debug.test;

import android.app.Activity;
import android.content.Intent;


import com.hunter.library.debug.HunterDebugClass;
import com.hunter.library.debug.HunterDebugImpl;
import com.hunter.library.debug.HunterDebugSkip;



@HunterDebugClass
public class ClassTest {



    public String test1(int age){
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
            return "fail";
        }

        return "success";
    }

//    private void test2(String name,int age){
//        throw new RuntimeException("not impl");
//    }

    protected void test3(Intent intent,String age){

    }

    public static void test4(Activity activity,String ...args){

    }
}
-----------------------------------
transform后的class文件：
package com.quinn.hunter.debug.test;

import android.app.Activity;
import android.content.Intent;
import com.hunter.library.debug.HunterDebugClass;
import com.hunter.library.debug.ParameterPrinter;
import com.hunter.library.debug.ResultPrinter;

@HunterDebugClass
public class ClassTest {
    public ClassTest() {
        new ParameterPrinter("ClassTest", "<init>").print();
        ResultPrinter.print("ClassTest", "<init>", System.currentTimeMillis() - System.currentTimeMillis(), (Object) "void");
    }

    public String test1(int i) {
        ParameterPrinter parameterPrinter = new ParameterPrinter("ClassTest", "test1");
        parameterPrinter.append("age", i);
        parameterPrinter.print();
        long currentTimeMillis = System.currentTimeMillis();
        try {
            Thread.sleep(1000);
            Object obj = "success";
            ResultPrinter.print("ClassTest", "test1", System.currentTimeMillis() - currentTimeMillis, obj);
            return obj;
        } catch (InterruptedException e) {
            e.printStackTrace();
            Object obj2 = "fail";
            ResultPrinter.print("ClassTest", "test1", System.currentTimeMillis() - currentTimeMillis, obj2);
            return obj2;
        }
    }

    /* Access modifiers changed, original: protected */
    public void test3(Intent intent, String str) {
        ParameterPrinter parameterPrinter = new ParameterPrinter("ClassTest", "test3");
        parameterPrinter.append("intent", (Object) intent);
        parameterPrinter.append("age", (Object) str);
        parameterPrinter.print();
        ResultPrinter.print("ClassTest", "test3", System.currentTimeMillis() - System.currentTimeMillis(), (Object) "void");
    }

    public static void test4(Activity activity, String... strArr) {
        ParameterPrinter parameterPrinter = new ParameterPrinter("ClassTest", "test4");
        parameterPrinter.append("activity", (Object) activity);
        parameterPrinter.append("args", (Object) strArr);
        parameterPrinter.print();
        ResultPrinter.print("ClassTest", "test4", System.currentTimeMillis() - System.currentTimeMillis(), (Object) "void");
    }
}


对比文件2:
package com.quinn.hunter.debug.test;

import android.app.Activity;
import android.content.Intent;


import com.hunter.library.debug.HunterDebugClass;
import com.hunter.library.debug.HunterDebugImpl;
import com.hunter.library.debug.HunterDebugSkip;



@HunterDebugClass
public class ClassTest2 {


    @HunterDebugSkip
    public String test1(int age){
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
            return "fail";
        }

        return "success";
    }

//    private void test2(String name,int age){
//        throw new RuntimeException("not impl");
//    }

    @HunterDebugImpl
    protected void test3(Intent intent,String age){

    }

    @HunterDebugImpl
    public static void test4(Activity activity,String ...args){

    }
}

--------------------------------
transform后的文件
package com.quinn.hunter.debug.test;

import android.app.Activity;
import android.content.Intent;
import com.hunter.library.debug.HunterDebugClass;
import com.hunter.library.debug.HunterDebugImpl;
import com.hunter.library.debug.HunterDebugSkip;
import com.hunter.library.debug.ParameterPrinter;
import com.hunter.library.debug.ResultPrinter;

@HunterDebugClass
public class ClassTest2 {
    public ClassTest2() {
        new ParameterPrinter("ClassTest2", "<init>").print();
        ResultPrinter.print("ClassTest2", "<init>", System.currentTimeMillis() - System.currentTimeMillis(), (Object) "void");
    }

    @HunterDebugSkip
    public String test1(int age) {
        try {
            Thread.sleep(1000);
            return "success";
        } catch (InterruptedException e) {
            e.printStackTrace();
            return "fail";
        }
    }

    /* Access modifiers changed, original: protected */
    @HunterDebugImpl
    public void test3(Intent intent, String str) {
        ParameterPrinter parameterPrinter = new ParameterPrinter("ClassTest2", "test3");
        parameterPrinter.append("intent", (Object) intent);
        parameterPrinter.append("age", (Object) str);
        parameterPrinter.printWithCustomLogger();
        ResultPrinter.printWithCustomLogger("ClassTest2", "test3", System.currentTimeMillis() - System.currentTimeMillis(), (Object) "void");
    }

    @HunterDebugImpl
    public static void test4(Activity activity, String... strArr) {
        ParameterPrinter parameterPrinter = new ParameterPrinter("ClassTest2", "test4");
        parameterPrinter.append("activity", (Object) activity);
        parameterPrinter.append("args", (Object) strArr);
        parameterPrinter.printWithCustomLogger();
        ResultPrinter.printWithCustomLogger("ClassTest2", "test4", System.currentTimeMillis() - System.currentTimeMillis(), (Object) "void");
    }
}

**Comment by Leaking** [comment]
已merge 
https://github.com/Leaking/Hunter/pull/20
