### ISSUE TITLE
Global OKHttp Interceptor - Working with multiple modules / libraries

### ISSUE THREAD

**Issue by behelit** [Leaking/Hunter#2]
Should this work with sub modules? i.e. I have set up the okhttphooker in my MainActivity but also use okhttp clients in my library modules.

At the moment it does not appear to be working as I would have expected it. If it should, I will try to create a sample project of what I'm doing.

**Comment by Leaking** [comment]
> Should this work with sub modules? i.e. I have set up the okhttphooker in my MainActivity but also use okhttp clients in my library modules.
> 
> At the moment it does not appear to be working as I would have expected it. If it should, I will try to create a sample project of what I'm doing.

Have a try: https://github.com/Leaking/Hunter-Okhttp-Sample

May I close this issue ?

**Comment by behelit** [comment]
Sorry, that's what I meant. I did try it and used the global installation to apply authentication to the okhttpclient but it didn't seem to add them. 
Please note, the same authentication works when I add it manually as an interceptor but this was from within the module I'm using for REST, and not the 'app' module.

I think the 'install' may not be applying to okhttp clients that are instantiated in sub modules? (non 'app' module)

**Comment by Leaking** [comment]
when do you call the inatall method.  it should be called before your module's okhttpclient initial.  Can you show me a sample project？

**Comment by qzcsfchh** [comment]
Hunter-Okhttp-Sample和本项目的代码都拉下来跑了，但是两个都不起作用，CustomGlobalInterceptor的日志都不打印，代码也没有执行，可能是哪里出了问题呢？

**Comment by Leaking** [comment]
@qzcsfchh 
你是使用Mac还是window呢？
我在Mac上运行没什么问题。
如果你是使用windows，重新pull一下代码，我改了一下编译插件的依赖，之前readme更新了，example代码忘了更新。

试试看，有问题欢迎继续反馈给我

**Comment by qzcsfchh** [comment]
@Leaking 还是不行，我的环境是win10，试了两台电脑都不行

**Comment by Leaking** [comment]
@qzcsfchh  我找了台win10机器定位到问题了，已经提交bugfix，你更新一下gradle依赖，重新clean build一次，应该就可以了
hunter-okhttp-plugin更新为 0.9.2了

```groovy
 classpath 'com.quinn.hunter:hunter-okhttp-plugin:0.9.2'
 classpath 'com.quinn.hunter:hunter-transform:0.9.3'
```

**Comment by Leaking** [comment]
@behelit  you come across this bug in Windows or mac ?

**Comment by qzcsfchh** [comment]
@Leaking 测试可以了👍
