### ISSUE TITLE
ClassWriter getCommonSuperClass

### ISSUE THREAD

**Issue by xymelon** [Leaking/Hunter#25]
请问getCommonSuperClass什么场景会用到导致出错呢？
主要是我之前写了个较简单的字节码修改第三方代码的gradle plugin，未遇到出错的情况。

**Comment by Leaking** [comment]
> 请问getCommonSuperClass什么场景会用到导致出错呢？
> 主要是我之前写了个较简单的字节码修改第三方代码的gradle plugin，未遇到出错的情况。

@xymelon 
记得后来我研究了一遍，这个getCommonSuperClass出问题的情况，好像需要ClassWriter构建时使用COMPUTE_FRAMES才可能出现，我现在项目中使用COMPUTE_MAX是不会出现了。

之前对比过COMPUTE_MAX 和 COMPUTE_FRAMES，前者速度是更快的。

**Comment by xymelon** [comment]
@Leaking 感谢 我再研究下
