### ISSUE TITLE
针对jar的内容需要更改的场景疑惑。

### ISSUE THREAD

**Issue by YummyLau** [Leaking/Hunter#27]
您好，作者。最近在做一个代码扫描并使用asm插入字节码的插件。通过扫描项目注解得到一些map，然后针对map使用asm插入到一个jar的init方法里面做初始化干预。在第一次transform全量插入成功（内容记录为A），第二次由于我们HunterTransform开了增量，在第二次transform过程中发现jar的内容没有发生改变就跳过了插入新更改的内容（内容记录为B，跳过是因为还没有更改，陷于鸡生蛋的问题）。
尝试两种办法：
1. 新增的B内容，根据判断要插入的jar的位置定位到jar，然后继续追加插入，但是有一些小问题，比如变化的内容可能涉及到增删改，可能和第一次插入的旧的内容会有冲突导致业务逻辑错误；
2. 需要保存A内容，然后diff 前后两次内容得到最后的内容，覆盖掉第一次插入的内容。
针对这样的处理，是否有更好的建议。

**Comment by Leaking** [comment]
> 通过扫描项目注解得到一些map，然后针对map使用asm插入到一个jar的init方法里面做初始化干预。
这里是在编译期间，从代码里扫描出这个Map吗？然后再使用ASM将这个Map的内容生成初始化的代码？

**Comment by Leaking** [comment]
如果我上面的理解对的话，感觉插入的字节码的方式可以改一下。
可以在jar包某个你要干预的地方，插入一个静态工具方法就行，然后这个静态工具方法的实现，你可以在你的源码里写，这样就很方便了。

**Comment by YummyLau** [comment]
嗯嗯明白了。谢谢
