### ISSUE TITLE
不能兼容library module：com.quinn.hunter.transform.asm.ClassLoaderHelper#getAndroidJarPath

### ISSUE THREAD

**Issue by legendmohe** [Leaking/Hunter#29]
在Library中apply plugin，com.quinn.hunter.transform.asm.ClassLoaderHelper#getAndroidJarPath这一句会直接崩掉，建议修改(AppExtension)project.getProperties().get("android");一句的实现以兼容library

**Comment by Leaking** [comment]
transform暂时不支持 library，会抛出这个异常

> Transforms with scopes '[SUB_PROJECTS, EXTERNAL_LIBRARIES]' cannot be applied to library projects.

**Comment by legendmohe** [comment]
> transform暂时不支持 library，会抛出这个异常
> 
> > Transforms with scopes '[SUB_PROJECTS, EXTERNAL_LIBRARIES]' cannot be applied to library projects.

好的。我自己fork然后改成支持的了。
