### ISSUE TITLE
请教一下, 为什么在使用AsyncTask<Void, Integer, Boolean>时, 每个Override方法都会打印两遍

### ISSUE THREAD

**Issue by zuilintan** [Leaking/Hunter#30]
发现这个问题后, 我彻查一遍代码, 没有发现asyncTask.execute()的多次执行, 
奇怪的是打印的两次, 第一次是没有形参的, 第二次是我Override的有形参的方法, 并且都在同一线程内, 
后来一步步排查发现, 将我原本的extends AsyncTask<Void, Integer, Boolean>修改未extents AsyncTask, 
也就是去掉泛型, 方法就正常打印一次了

**Comment by zuilintan** [comment]
泛型的特性, 无法实现

**Comment by Leaking** [comment]
兄弟好积极，要不扫码进微信群和其他人探讨探讨？

**Comment by zuilintan** [comment]
hah, 可以呀
