### ISSUE TITLE
另一个程序正在使用此文件，进程无法访问

### ISSUE THREAD

**Issue by Alex-Cin** [Leaking/Hunter#35]
D:\workspace\studio\AF\gradle-build\app_abundant\intermediates\transforms\ATransform\debug\475.jar: 另一个程序正在使用此文件，进程无法访问。

频率不是很高，但是经常出现。

**Comment by Alex-Cin** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clean'.
> Unable to delete directory 'D:\workspace\studio\AF\gradle-build'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - D:\workspace\studio\AF\gradle-build\app_abundant\intermediates\transforms\CostTimeTransform\debug\69.jar
    - D:\workspace\studio\AF\gradle-build\app_abundant\intermediates\transforms\CostTimeTransform\debug\75.jar
    - D:\workspace\studio\AF\gradle-build\app_abundant\intermediates\transforms\CostTimeTransform\debug
    - D:\workspace\studio\AF\gradle-build\app_abundant\intermediates\transforms\CostTimeTransform
    - D:\workspace\studio\AF\gradle-build\app_abundant\intermediates\transforms
    - D:\workspace\studio\AF\gradle-build\app_abundant\intermediates
    - D:\workspace\studio\AF\gradle-build\app_abundant

**Comment by xuyunyu** [comment]
遇到同样的问题，大佬有解决吗？

**Comment by Leaking** [comment]
> 遇到同样的问题，大佬有解决吗？

使用最新的版本试试。
```
classpath 'com.quinn.hunter:hunter-transform:1.2.1'
```

**Comment by Leaking** [comment]
> 遇到同样的问题，大佬有解决吗？

这个问题是因为transform之前没有close jar包的文件流导致的。在这个[PR](https://github.com/Leaking/Hunter/pull/51#event-6311177746)里fix了。
可以先先尝试在任务管理器，退出所有Java进程（其中一些可能是遗留的gradle damon进程），然后再升级上面的1.2.1版本试试。
