### ISSUE TITLE
能否兼容ASM 6?

### ISSUE THREAD

**Issue by zuilintan** [Leaking/Hunter#37]
Gson 2.8.6后使用ASM6, 
Lombok亦然, 
二者都无法与Hunter共存, 令寿头大

**Comment by Leaking** [comment]
这两周争取支持

**Comment by Leaking** [comment]
@zuilintan  支持了，请阅读readme，升级到最新1.0.0版本

**Comment by tuancoltech** [comment]
> @zuilintan upgraded to 6.0, please read the readme to upgrade to the latest version 1.0.0

@Leaking It seems the version `1.0.0` has not been pushed to remote repo yet.
I'm having version resolution issue.
Can you take a look please?

`Failed to resolve: com.quinn.hunter:hunter-debug-library:1.0.0`

**Comment by Leaking** [comment]
@zuilintan  再试试最新版本哈，1.1.0

**Comment by zuilintan** [comment]
验证OK, 感谢~
