### ISSUE TITLE
1.0.0依然无法兼容Gson 2.8.6

### ISSUE THREAD

**Issue by zuilintan** [Leaking/Hunter#39]
![image](https://user-images.githubusercontent.com/34953840/92347024-45691f80-f101-11ea-80a8-ab6aac02f409.png)
将Gson改为2.8.5没问题, 或者将hunterdebug注掉

**Comment by zuilintan** [comment]
在"Make"时报错

**Comment by weikaiyun** [comment]
> 在"Make"时报错

试试最新版本
