### ISSUE TITLE
OKhttp的问题

### ISSUE THREAD

**Issue by wcglws** [Leaking/Hunter#4]
OKhttp的插件对 OKhttp的版本有要求么？

**Comment by Leaking** [comment]
> OKhttp的插件对 OKhttp的版本有要求么？

目前有要求，需要3.11，因为处理了[3.11引入的EventListener](https://github.com/square/okhttp/wiki/Events)

可以考虑处理兼容低版本的情况

**Comment by Leaking** [comment]
> OKhttp的插件对 OKhttp的版本有要求么？

已经支持3.11以下版本，请查看这里 https://github.com/Leaking/Hunter/wiki/Okhttp-below-3.11

不过我还是推荐将项目中的Okhttp尽量升级到3.11或者更新版本，升级Okhttp的成本很低，而且能获得okhttp的最新优化和bugfix
