### ISSUE TITLE
请教下，增量编译的时候为什么【ADD】不处理？不太理解

### ISSUE THREAD

**Issue by miqt** [Leaking/Hunter#46]
代码位置：
https://github.com/Leaking/Hunter/blob/87e8af3a8c01a4bdb6e8e9f31b1ae1c4e8e9300f/hunter-transform/src/main/java/com/quinn/hunter/transform/HunterTransform.java#L155

**Comment by Leaking** [comment]
这个case没break，和下面的case一起处理

**Comment by miqt** [comment]
> 这个case没break，和下面的case一起处理

大意了
