### ISSUE TITLE
请问作者现在maven密码应该怎么填，验证不通过呢

### ISSUE THREAD

**Issue by maocanmao** [Leaking/Hunter#53]
Required by:
         project :hunter-debug-example
      > Could not resolve com.quinn.hunter:hunter-debug-plugin:1.2.0.
         > Could not get resource 'https://maven.pkg.github.com/Leaking/Hunter/com/quinn/hunter/hunter-debug-plugin/1.2.0/hunter-debug-plugin-1.2.0.pom'.
            > Could not GET 'https://maven.pkg.github.com/Leaking/Hunter/com/quinn/hunter/hunter-debug-plugin/1.2.0/hunter-debug-plugin-1.2.0.pom'. Received status code 401 from server: Unauthorized

**Comment by Leaking** [comment]
@maocanmao  try new credentials password

```
credentials {
    username = 'Leaking'
    password = '\u0067\u0068\u0070\u005f\u0072\u006a\u0041\u004b\u0037\u006d\u0048\u0047\u006b\u0031\u0045\u0039\u0063\u0048\u0044\u0076\u004f\u0039\u0078\u006f\u0046\u0048\u004d\u0049\u0032\u006a\u0047\u0057\u0047\u0068\u0032\u0036\u0065\u0075\u0043\u006b'
}

```

**Comment by Leaking** [comment]
@maocanmao  是否恢复正常了呢
