### ISSUE TITLE
文档错误：Maven坐标不对

### ISSUE THREAD

**Issue by qzcsfchh** [Leaking/Hunter#57]
![image](https://user-images.githubusercontent.com/17892408/182810700-129d29e6-b202-4fae-b309-da55b8854e10.png)
对应的Maven坐标应为：

```
classpath "cn.quinnchen.hunter:hunter-debug-plugin:${LATEST_VERSION_IN_README}"
classpath "cn.quinnchen.hunter:hunter-transform:${LATEST_VERSION_IN_README}"


implementation "cn.quinnchen.hunter:hunter-debug-library:${LATEST_VERSION_IN_README}"
...


```
区别是：`quinn`-->`quinnchen`

**Comment by Leaking** [comment]
> ![image](https://user-images.githubusercontent.com/17892408/182810700-129d29e6-b202-4fae-b309-da55b8854e10.png) 对应的Maven坐标应为：
> 
> ```
> classpath "cn.quinnchen.hunter:hunter-debug-plugin:${LATEST_VERSION_IN_README}"
> classpath "cn.quinnchen.hunter:hunter-transform:${LATEST_VERSION_IN_README}"
> 
> 
> implementation "cn.quinnchen.hunter:hunter-debug-library:${LATEST_VERSION_IN_README}"
> ...
> ```
> 
> 区别是：`quinn`-->`quinnchen`

多谢。提一个MR给我？我直接合并你的修改

**Comment by qzcsfchh** [comment]
可以啊，稍后我提交一下
