### ISSUE TITLE
设置了runVariant = 'DEBUG'，release包依然会打印log

### ISSUE THREAD

**Issue by imxy** [Leaking/Hunter#8]

**Comment by imxy** [comment]
我是在app module 的gradle文件设置的，然后 base module 依赖 
api 'com.quinn.hunter:hunter-debug-library:0.9.4'，两个module的@HunterDebug注解的方法都会打印
（app 依赖的 base module）

**Comment by Leaking** [comment]
我暂时没复现你说的这个情况。能否新建一个小demo复现你说的这个情况，然后把demo放到GitHub，我去clone下来看看。谢谢

**Comment by imxy** [comment]
新建demo release包不会打印，但是我现在的项目依然会。。。 @Leaking

**Comment by Leaking** [comment]
> https://github.com/imxy/pubgassist
> 我设置了 NERVER，但是还是会打印。。。
> 注解的MainActivity 的 initView()方法
> @Leaking

拉你这个工程依然编译正常，并没有打印，，，你试试clean build一次，

可以看看编译日志，emptyRun表示不修改字节码

···xml
> Task :app:transformClassesWithDebugHunterTransformForDebug
DebugHunterTransform isIncremental = false, runVariant = NEVER, emptyRun = true, inDuplcatedClassSafeMode = false
DebugHunterTransform costed 199ms

> Task :app:transformClassesWithDebugHunterTransformForRelease
DebugHunterTransform isIncremental = false, runVariant = NEVER, emptyRun = true, inDuplcatedClassSafeMode = false
DebugHunterTransform costed 176ms
···

**Comment by Leaking** [comment]
@imxy  确定没问题的话，可以close这个issue吗

**Comment by imxy** [comment]
@Leaking 带会儿我有空试试

**Comment by Leaking** [comment]
我先关了这个issue，确认有问题后，再打开也可以

**Comment by imxy** [comment]
@Leaking 更改配置之后确实需要clean再build才能生效
