### ISSUE TITLE
似乎对windows路径支持不好，能否把“/”换成File.separator？

### ISSUE THREAD

**Issue by xingchenxuanfeng** [Leaking/Hunter#9]
似乎对windows路径支持不好，能否把“/”换成File.separator？

目前发现BaseWeaver的weaveSingleClassToFile方法中的路径处理，都是用的“/”，在windows上应该是"\",
只要统一把所有的"/"符号换成File.separator就能正常处理路径了。

**Comment by Leaking** [comment]
嗯，这里处理不大妥当
我已经修改了，你可以验证下

另外，改了依赖的引入方式，现在编译脚本需要两个依赖

```groovy
classpath 'com.quinn.hunter:hunter-okhttp-plugin:0.9.1'
classpath 'com.quinn.hunter:hunter-transform:0.9.2'`
```

**Comment by xingchenxuanfeng** [comment]
我试了一下，0.9.2可以了。大神，给你点赞！

**Comment by Leaking** [comment]
@xingchenxuanfeng  

上次改这个bug引入了另一个问题，最好更新一下依赖

```groovy
classpath 'com.quinn.hunter:hunter-transform:0.9.3'
```

#11

**Comment by xingchenxuanfeng** [comment]
@Leaking 谢谢提醒，我这就更新到0.9.3
